# Generated by Django 4.1.2 on 2022-10-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=512, verbose_name='User email')),
                ('password', models.CharField(max_length=32, verbose_name='Password')),
                ('name', models.CharField(max_length=32, verbose_name='User name')),
                ('surname', models.CharField(max_length=32, verbose_name='User surname')),
            ],
        ),
    ]
