version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./compose/Dockerfile
    command: runserver
    volumes:
      - ./backend/app/:/app
    ports:
      - "8000:8000"